---
title: "MetaGraphs"
author: "S. Aguinaga"
date: "2/21/2015"
output: html_document
---
</br>
<h2>Working Folder</h2>
- dsg1:/data/saguinag/MetaGraphs

<h2>Datasets</h2>

- DBLP
- IMDB

*DBLP* 

*IMDB* Datasets are available at `idmb_data/`

<h2>Data Preparation </h2>


- *IMDB* 
Original (.list) files are parsed into a set of CSV files for movies (titles), actors, and actresses.  An inner join results into a data.frame that contains 
the titles and authors in those movies.  From these data.frame vertices 
and edges output files are created, then concatenated into a single SUBDUE graph
format input-file (.g).



<h2>Toy Graph</h2>

Selecting 10 lines from our dataset yields 13 vertices.  Looking at this toy dataset where AR = Actor, MO = Movie title, and edges are of type "WasIn":


```{r, echo=FALSE}
# from http://www.r-bloggers.com/network-visualization-in-r-with-the-igraph-package
require(igraph)
# Load the data. The data needs to be loaded as a table first: 
bsk<-read.table("imdb_data/imdb_10.ig") 
bsk.network<-graph.data.frame(bsk, directed=T) #the 'directed' attribute specifies whether the edges are directed
plot(bsk.network)
```

* Vertices and Edges

`v 1 AR`
`v 2 AR`
`v 3 AR`
`v 4 MO`
`v 5 MO`
`v 6 MO`
`v 7 MO`
`v 8 MO`
`v 9 MO`
`v 10  MO`
`v 11  MO`
`v 12  MO`
`v 13  MO`
`e 1 12  WasIn`
`e 1 13  WasIn`
`e 2 9 WasIn`
`e 3 4 WasIn`
`e 3 5 WasIn`
`e 3 6 WasIn`
`e 3 7 WasIn`
`e 3 8 WasIn`
`e 3 10  WasIn`
`e 3 11  WasIn`

SUBDUE finds 2 instances of MO<--AR-->MO as the most frequent subgraph (most frequent where nodes don't repeat).  In this case, the structure does repeat where node 3 is the root, see this in th figure.

The best FSG found in this toy example and the embeddings Graph(3v,2e):

Node | Node|Link|
-----|-----|----|
Edge | Id  |Type|
v    | 1   | AR
v    | 2   | MO
v    | 3   | MO
d    | 1 2 | WasIn
d    | 1 3 | WasIn
